"""add token_emergencia column to solicitudes

Revision ID: 07c742aefb9c
Revises: f2b57afd3421
Create Date: 2026-03-14 01:25:05.546703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c742aefb9c'
down_revision: Union[str, None] = 'f2b57afd3421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes', sa.Column('token_emergencia', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes', 'token_emergencia')
    # ### end Alembic commands ###
