"""aumentar longitud campo tipo a 30

Revision ID: 18cdbf146430
Revises: 5d3577d24cd6
Create Date: 2026-03-04 01:29:22.271782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18cdbf146430'
down_revision: Union[str, None] = '5d3577d24cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qr_registros_empleado', table_name='qr_registros')
    op.drop_index('idx_qr_registros_expiracion', table_name='qr_registros')
    op.drop_index('idx_qr_registros_qr_id', table_name='qr_registros')
    op.drop_index('idx_qr_registros_usado', table_name='qr_registros', postgresql_where='(usado = false)')
    op.drop_table('qr_registros')
    op.alter_column('solicitudes_cambio', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index('idx_solicitudes_created_at', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_empleado2_id', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_empleado_id', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_estado', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_fecha', table_name='solicitudes_cambio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_solicitudes_fecha', 'solicitudes_cambio', ['fecha_cambio'], unique=False)
    op.create_index('idx_solicitudes_estado', 'solicitudes_cambio', ['estado'], unique=False)
    op.create_index('idx_solicitudes_empleado_id', 'solicitudes_cambio', ['empleado_id'], unique=False)
    op.create_index('idx_solicitudes_empleado2_id', 'solicitudes_cambio', ['empleado2_id'], unique=False)
    op.create_index('idx_solicitudes_created_at', 'solicitudes_cambio', [sa.text('created_at DESC')], unique=False)
    op.alter_column('solicitudes_cambio', 'tipo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('qr_registros',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('qr_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('empleado_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('generado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expira_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('usado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('usado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('usado_por', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['personal.id'], name='qr_registros_empleado_id_fkey'),
    sa.ForeignKeyConstraint(['usado_por'], ['usuarios.id'], name='qr_registros_usado_por_fkey'),
    sa.PrimaryKeyConstraint('id', name='qr_registros_pkey'),
    sa.UniqueConstraint('qr_id', name='qr_registros_qr_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_qr_registros_usado', 'qr_registros', ['usado'], unique=False, postgresql_where='(usado = false)')
    op.create_index('idx_qr_registros_qr_id', 'qr_registros', ['qr_id'], unique=False)
    op.create_index('idx_qr_registros_expiracion', 'qr_registros', ['expira_en'], unique=False)
    op.create_index('idx_qr_registros_empleado', 'qr_registros', ['empleado_id'], unique=False)
    # ### end Alembic commands ###
