"""crear todas las tablas (corregido)

Revision ID: 5d3577d24cd6
Revises: 
Create Date: 2026-03-01 01:02:19.945289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3577d24cd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('cip', sa.String(length=20), nullable=False),
    sa.Column('grado', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('condicion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cip'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personal_area'), 'personal', ['area'], unique=False)
    op.create_index(op.f('ix_personal_dni'), 'personal', ['dni'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('asistencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tipo_registro', sa.String(length=10), nullable=False),
    sa.Column('turno_codigo', sa.String(length=10), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descansos_medicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico_cie', sa.String(length=10), nullable=True),
    sa.Column('diagnostico_desc', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('domicilio', sa.JSON(), nullable=False),
    sa.Column('profesional', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('anotaciones', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno_codigo', sa.String(length=10), nullable=False),
    sa.Column('observacion', sa.String(length=500), nullable=True),
    sa.Column('dm_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_id', 'fecha', name='unique_personal_fecha')
    )
    op.create_table('solicitudes_cambio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('empleado2_id', sa.UUID(), nullable=True),
    sa.Column('turno_original', sa.JSON(), nullable=True),
    sa.Column('turno_solicitado', sa.JSON(), nullable=True),
    sa.Column('turno_original_solicitante', sa.JSON(), nullable=True),
    sa.Column('turno_original_colega', sa.JSON(), nullable=True),
    sa.Column('turno_solicitante_recibe', sa.JSON(), nullable=True),
    sa.Column('turno_colega_recibe', sa.JSON(), nullable=True),
    sa.Column('validacion_dias_libres', sa.JSON(), nullable=True),
    sa.Column('documentos', sa.JSON(), nullable=True),
    sa.Column('historial', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_por', sa.UUID(), nullable=True),
    sa.Column('comentario_revision', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado2_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_cambio')
    op.drop_table('planificacion')
    op.drop_table('descansos_medicos')
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_personal_dni'), table_name='personal')
    op.drop_index(op.f('ix_personal_area'), table_name='personal')
    op.drop_table('personal')
    # ### end Alembic commands ###
