"""add solicitudes trazabilidad jerarquia tables

Revision ID: f2b57afd3421
Revises: 18cdbf146430
Create Date: 2026-03-14 00:31:10.240084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b57afd3421'
down_revision: Union[str, None] = '18cdbf146430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jerarquia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_area', sa.String(length=50), nullable=False),
    sa.Column('nombre_area', sa.String(length=100), nullable=False),
    sa.Column('tipo_area', sa.Enum('DEPARTAMENTO', 'SECCION', 'SERVICIO', 'UNIDAD', 'OTRO', name='tipoarea'), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('rol_requerido', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('jefe_id', sa.UUID(), nullable=True),
    sa.Column('puede_aprobar_misma_area', sa.Boolean(), nullable=True),
    sa.Column('puede_aprobar_areas_hijas', sa.Boolean(), nullable=True),
    sa.Column('limite_aprobacion', sa.JSON(), nullable=True),
    sa.Column('personal_ids', sa.JSON(), nullable=True),
    sa.Column('subareas_ids', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jefe_id'], ['jerarquia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_area', 'nivel', 'usuario_id', name='uq_area_nivel_usuario')
    )
    op.create_index(op.f('ix_jerarquia_codigo_area'), 'jerarquia', ['codigo_area'], unique=False)
    op.create_table('solicitudes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PROPIO', 'INTERCAMBIO', 'PLANIFICACION_MENSUAL', 'VACACIONES', 'PERMISO', 'DESCANSO_MEDICO', 'LICENCIA', 'CAPACITACION', 'OTRO', name='tiposolicitud'), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE', 'EN_APROBACION', 'APROBADA', 'RECHAZADA', 'OBSERVADA', 'CANCELADA', name='estadosolicitud'), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('empleado2_id', sa.UUID(), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=True),
    sa.Column('nivel_maximo', sa.Integer(), nullable=False),
    sa.Column('validacion_dias_libres', sa.JSON(), nullable=True),
    sa.Column('documentos', sa.JSON(), nullable=True),
    sa.Column('meta_datos', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_por', sa.UUID(), nullable=True),
    sa.Column('comentario_revision', sa.Text(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprobado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empleado2_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_empleado_id'), 'solicitudes', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_estado'), 'solicitudes', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_tipo'), 'solicitudes', ['tipo'], unique=False)
    op.create_table('trazabilidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solicitud_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.Enum('CREACION', 'ENVIO', 'APROBACION', 'RECHAZO', 'OBSERVACION', 'CANCELACION', 'MODIFICACION', 'VISUALIZACION', 'DESCARGA_QR', 'VALIDACION_QR', 'SUBIDA_DOCUMENTO', 'NOTIFICACION', name='acciontrazabilidad'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_solicitud', sa.String(length=64), nullable=False),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_actual', sa.String(length=64), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_actual')
    )
    op.create_index(op.f('ix_trazabilidad_accion'), 'trazabilidad', ['accion'], unique=False)
    op.create_index(op.f('ix_trazabilidad_created_at'), 'trazabilidad', ['created_at'], unique=False)
    op.create_index(op.f('ix_trazabilidad_solicitud_id'), 'trazabilidad', ['solicitud_id'], unique=False)
    op.alter_column('configuraciones_mensuales', 'turnos_base',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('configuraciones_mensuales', 'observacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('configuraciones_mensuales', 'validado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('configuraciones_mensuales', 'historial',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_configuracion_año', table_name='configuraciones_mensuales')
    op.drop_index('idx_configuracion_mes', table_name='configuraciones_mensuales')
    op.drop_index('idx_configuracion_validado_por', table_name='configuraciones_mensuales')
    op.create_index(op.f('ix_configuraciones_mensuales_año'), 'configuraciones_mensuales', ['año'], unique=False)
    op.create_index(op.f('ix_configuraciones_mensuales_id'), 'configuraciones_mensuales', ['id'], unique=False)
    op.create_index(op.f('ix_configuraciones_mensuales_mes'), 'configuraciones_mensuales', ['mes'], unique=False)
    op.drop_index('idx_descansos_fechas_estado', table_name='descansos_medicos')
    op.alter_column('personal', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_personal_area_id', table_name='personal')
    op.alter_column('planificacion_borradores', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('planificacion_borradores', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('planificacion_borradores', 'datos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_planificacion_borrador_mes_anio', table_name='planificacion_borradores')
    op.alter_column('qr_registros', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('qr_registros', 'generado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_registros', 'usado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_qr_registros_empleado', table_name='qr_registros')
    op.drop_index('idx_qr_registros_expiracion', table_name='qr_registros')
    op.drop_index('idx_qr_registros_qr_id', table_name='qr_registros')
    op.drop_index('idx_qr_registros_usado', table_name='qr_registros', postgresql_where='(usado = false)')
    op.drop_constraint('qr_registros_qr_id_key', 'qr_registros', type_='unique')
    op.create_index(op.f('ix_qr_registros_qr_id'), 'qr_registros', ['qr_id'], unique=True)
    op.drop_index('idx_solicitudes_created_at', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_empleado2_id', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_empleado_id', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_estado', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_fecha', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_fecha_cambio', table_name='solicitudes_cambio')
    op.drop_index('idx_solicitudes_tipo_estado_empleado', table_name='solicitudes_cambio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_solicitudes_tipo_estado_empleado', 'solicitudes_cambio', ['tipo', 'estado', 'empleado_id'], unique=False)
    op.create_index('idx_solicitudes_fecha_cambio', 'solicitudes_cambio', ['fecha_cambio'], unique=False)
    op.create_index('idx_solicitudes_fecha', 'solicitudes_cambio', ['fecha_cambio'], unique=False)
    op.create_index('idx_solicitudes_estado', 'solicitudes_cambio', ['estado'], unique=False)
    op.create_index('idx_solicitudes_empleado_id', 'solicitudes_cambio', ['empleado_id'], unique=False)
    op.create_index('idx_solicitudes_empleado2_id', 'solicitudes_cambio', ['empleado2_id'], unique=False)
    op.create_index('idx_solicitudes_created_at', 'solicitudes_cambio', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_qr_registros_qr_id'), table_name='qr_registros')
    op.create_unique_constraint('qr_registros_qr_id_key', 'qr_registros', ['qr_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_qr_registros_usado', 'qr_registros', ['usado'], unique=False, postgresql_where='(usado = false)')
    op.create_index('idx_qr_registros_qr_id', 'qr_registros', ['qr_id'], unique=False)
    op.create_index('idx_qr_registros_expiracion', 'qr_registros', ['expira_en'], unique=False)
    op.create_index('idx_qr_registros_empleado', 'qr_registros', ['empleado_id'], unique=False)
    op.alter_column('qr_registros', 'usado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('qr_registros', 'generado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('qr_registros', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_planificacion_borrador_mes_anio', 'planificacion_borradores', ['mes', 'año'], unique=False)
    op.alter_column('planificacion_borradores', 'datos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('planificacion_borradores', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'borrador'::character varying"),
               existing_nullable=False)
    op.alter_column('planificacion_borradores', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('idx_personal_area_id', 'personal', ['area', 'id'], unique=False)
    op.alter_column('personal', 'sexo',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'No especificado'::character varying"),
               existing_nullable=True)
    op.create_index('idx_descansos_fechas_estado', 'descansos_medicos', ['fecha_inicio', 'fecha_fin', 'estado'], unique=False)
    op.drop_index(op.f('ix_configuraciones_mensuales_mes'), table_name='configuraciones_mensuales')
    op.drop_index(op.f('ix_configuraciones_mensuales_id'), table_name='configuraciones_mensuales')
    op.drop_index(op.f('ix_configuraciones_mensuales_año'), table_name='configuraciones_mensuales')
    op.create_index('idx_configuracion_validado_por', 'configuraciones_mensuales', ['validado_por'], unique=False)
    op.create_index('idx_configuracion_mes', 'configuraciones_mensuales', ['mes'], unique=False)
    op.create_index('idx_configuracion_año', 'configuraciones_mensuales', ['año'], unique=False)
    op.alter_column('configuraciones_mensuales', 'historial',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('configuraciones_mensuales', 'validado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('configuraciones_mensuales', 'observacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('configuraciones_mensuales', 'turnos_base',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               existing_nullable=False)
    op.drop_index(op.f('ix_trazabilidad_solicitud_id'), table_name='trazabilidad')
    op.drop_index(op.f('ix_trazabilidad_created_at'), table_name='trazabilidad')
    op.drop_index(op.f('ix_trazabilidad_accion'), table_name='trazabilidad')
    op.drop_table('trazabilidad')
    op.drop_index(op.f('ix_solicitudes_tipo'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_estado'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_empleado_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    op.drop_index(op.f('ix_jerarquia_codigo_area'), table_name='jerarquia')
    op.drop_table('jerarquia')
    # ### end Alembic commands ###
